# Generic required properties for Kafka clients
bootstrap.servers=

key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.StringSerializer

topic=

# Java properties
ssl.truststore.certificates=
ssl.truststore.type=PEM
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="user" password="password";

client.id=

acks=all
enable.idempotence=true
